### ISSUE TITLE
Error with load - Just now

### ISSUE THREAD

**Issue by rohanabraham** [EOSIO/genesis#39]
1) git cloned
2) npm install
3) config.js created from the default
4) running snapshot, I get this error

$ node snapshot.js --load_config
module.js:549
    throw err;
    ^

Error: Cannot find module '../../config.default'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at waterfall (/home/ubuntu/genesis/genesis/tools/snapshot/index.js:37:33)
    at nextTask (/home/ubuntu/genesis/genesis/node_modules/async/dist/async.js:5310:14)
    at next (/home/ubuntu/genesis/genesis/node_modules/async/dist/async.js:5317:9)
    at /home/ubuntu/genesis/genesis/node_modules/async/dist/async.js:958:16
    at prompt.get (/home/ubuntu/genesis/genesis/tools/snapshot/index.js:19:13)
    at /home/ubuntu/genesis/genesis/node_modules/prompt/lib/prompt.js:336:32

**Comment by rohanabraham** [comment]
Very interesting,
I did a mv config.default.js to config.js and this error occurred
If I cp config.js to config.default.js, then it works.

It looks like the correct config.js is actually being used but the system requires config.default.js to be present!

**Comment by dskvr** [comment]
@rohanabraham Correct, do not remove config.default.js, that's why the instructions say **copy the file**. Config default is used to object assigned default values to the config object.

**Comment by dskvr** [comment]
@rohanabraham I've updated the docs to make this more clear, thanks for bringing it to my attention.

**Comment by rohanabraham** [comment]
@dskvr Thanks for updating the document, looks great!

PS: Thanks for all your work on this tool. We put together a space invaders game yesterday on EOS, the actual movements are transmitted via the blockchain and it works like magic! https://www.youtube.com/watch?v=k-5aG3YuyYk
